"""
WAF (Web Application Firewall) Detection Module

This module identifies the presence and type of WAF protecting a target application.
Understanding WAF presence is crucial for authorized penetration testing.
"""

import logging
import requests
import time
from typing import Dict, List, Any, Optional
from urllib.parse import urlparse, urljoin

logger = logging.getLogger(__name__)


class WAFDetector:
    """Detect and identify Web Application Firewalls"""

    # Known WAF signatures (HTTP headers, response patterns, etc.)
    WAF_SIGNATURES = {
        'Cloudflare': {
            'headers': ['cf-ray', 'cf-cache-status', '__cfduid'],
            'cookies': ['__cfduid', '__cflb'],
            'response_codes': [403, 503],
            'response_text': ['Attention Required', 'Cloudflare', 'Ray ID']
        },
        'AWS WAF': {
            'headers': ['x-amzn-requestid', 'x-amzn-trace-id'],
            'response_codes': [403],
            'response_text': ['AWS WAF', 'Request blocked']
        },
        'ModSecurity': {
            'headers': ['mod_security', 'NYOB'],
            'response_codes': [403, 406, 501],
            'response_text': ['ModSecurity', 'mod_security', 'Not Acceptable']
        },
        'Akamai': {
            'headers': ['akamai-origin-hop', 'x-akamai-transformed'],
            'response_codes': [403],
            'response_text': ['AkamaiGHost', 'Access Denied']
        },
        'Imperva (Incapsula)': {
            'headers': ['x-cdn', 'x-iinfo'],
            'cookies': ['incap_ses', 'visid_incap'],
            'response_codes': [403],
            'response_text': ['Incapsula', 'incapsula', '_Incapsula_Resource']
        },
        'Sucuri': {
            'headers': ['x-sucuri-id', 'x-sucuri-cache'],
            'response_codes': [403],
            'response_text': ['Sucuri WebSite Firewall', 'Questions?']
        },
        'Wordfence': {
            'headers': ['wordfence'],
            'response_codes': [403, 503],
            'response_text': ['Wordfence', 'Generated by Wordfence']
        },
        'F5 BIG-IP': {
            'headers': ['x-cnection', 'x-wa-info'],
            'cookies': ['TS', 'BIGipServer'],
            'response_codes': [403],
            'response_text': ['The requested URL was rejected']
        },
        'Barracuda': {
            'headers': ['barra_counter_session', 'barracuda_'],
            'cookies': ['barra_counter_session'],
            'response_codes': [403],
            'response_text': ['Barracuda', 'You have been blocked']
        }
    }

    # Payloads known to trigger WAF responses
    WAF_TRIGGER_PAYLOADS = [
        # SQL Injection triggers
        "' OR '1'='1",
        "1' AND 1=1--",
        "UNION SELECT NULL--",

        # XSS triggers
        "<script>alert('XSS')</script>",
        "javascript:alert(1)",
        "<img src=x onerror=alert(1)>",

        # Path traversal
        "../../../etc/passwd",
        "..\\..\\..\\windows\\win.ini",

        # Command injection
        "; ls -la",
        "| cat /etc/passwd",

        # XXE
        "<!DOCTYPE foo [<!ENTITY xxe SYSTEM 'file:///etc/passwd'>]>",
    ]

    def __init__(self, target_url: str, timeout: int = 10):
        """
        Initialize WAF detector

        Args:
            target_url: Target URL to test
            timeout: Request timeout in seconds
        """
        self.target_url = target_url
        self.timeout = timeout
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        })

        self.waf_detected = False
        self.waf_type = None
        self.waf_confidence = 0  # 0-100 confidence score
        self.evidence = []

    def detect_waf(self) -> Dict[str, Any]:
        """
        Perform comprehensive WAF detection

        Returns:
            Dictionary containing detection results
        """
        logger.info(f"Starting WAF detection on {self.target_url}")

        results = {
            'target': self.target_url,
            'waf_detected': False,
            'waf_type': 'None',
            'confidence': 0,
            'evidence': [],
            'rate_limiting': False,
            'recommendations': []
        }

        try:
            # Test 1: Baseline request
            baseline_response = self._make_baseline_request()
            if not baseline_response:
                results['error'] = 'Failed to establish baseline connection'
                return results

            # Test 2: Check headers and cookies
            header_results = self._check_headers_and_cookies(baseline_response)
            if header_results['detected']:
                results['waf_detected'] = True
                results['waf_type'] = header_results['waf_type']
                results['confidence'] = header_results['confidence']
                results['evidence'].extend(header_results['evidence'])

            # Test 3: Malicious payload testing
            payload_results = self._test_malicious_payloads()
            if payload_results['detected']:
                results['waf_detected'] = True
                if not results['waf_type'] or results['waf_type'] == 'None':
                    results['waf_type'] = payload_results.get('waf_type', 'Generic WAF')
                results['confidence'] = max(results['confidence'], payload_results['confidence'])
                results['evidence'].extend(payload_results['evidence'])

            # Test 4: Rate limiting detection
            rate_limit_results = self._test_rate_limiting()
            results['rate_limiting'] = rate_limit_results['detected']
            if rate_limit_results['detected']:
                results['evidence'].append(rate_limit_results['evidence'])

            # Test 5: Response analysis
            if not results['waf_detected']:
                # Check if generic WAF behavior detected
                if payload_results['blocked_requests'] > 0:
                    results['waf_detected'] = True
                    results['waf_type'] = 'Generic/Unknown WAF'
                    results['confidence'] = 50
                    results['evidence'].append(
                        f"Blocked {payload_results['blocked_requests']}/{payload_results['total_requests']} malicious requests"
                    )

            # Generate recommendations
            results['recommendations'] = self._generate_recommendations(results)

            logger.info(f"WAF detection complete: {results['waf_type']} (confidence: {results['confidence']}%)")

        except Exception as e:
            logger.error(f"WAF detection failed: {e}", exc_info=True)
            results['error'] = str(e)

        return results

    def _make_baseline_request(self) -> Optional[requests.Response]:
        """Make a baseline request to establish normal behavior"""
        try:
            response = self.session.get(self.target_url, timeout=self.timeout)
            logger.debug(f"Baseline request: {response.status_code}")
            return response
        except Exception as e:
            logger.error(f"Baseline request failed: {e}")
            return None

    def _check_headers_and_cookies(self, response: requests.Response) -> Dict[str, Any]:
        """Check response headers and cookies for WAF signatures"""
        results = {
            'detected': False,
            'waf_type': 'None',
            'confidence': 0,
            'evidence': []
        }

        # Check headers
        headers_lower = {k.lower(): v for k, v in response.headers.items()}
        cookies = {c.name for c in self.session.cookies}

        for waf_name, signatures in self.WAF_SIGNATURES.items():
            matches = 0
            total_checks = 0

            # Check headers
            if 'headers' in signatures:
                total_checks += len(signatures['headers'])
                for header in signatures['headers']:
                    if header.lower() in headers_lower:
                        matches += 1
                        results['evidence'].append(f"Header found: {header}")

            # Check cookies
            if 'cookies' in signatures:
                total_checks += len(signatures['cookies'])
                for cookie in signatures['cookies']:
                    if cookie in cookies:
                        matches += 1
                        results['evidence'].append(f"Cookie found: {cookie}")

            if matches > 0 and total_checks > 0:
                confidence = int((matches / total_checks) * 100)
                if confidence > results['confidence']:
                    results['detected'] = True
                    results['waf_type'] = waf_name
                    results['confidence'] = confidence

        return results

    def _test_malicious_payloads(self) -> Dict[str, Any]:
        """Test with malicious payloads to trigger WAF"""
        results = {
            'detected': False,
            'waf_type': None,
            'confidence': 0,
            'evidence': [],
            'blocked_requests': 0,
            'total_requests': 0
        }

        for payload in self.WAF_TRIGGER_PAYLOADS[:5]:  # Test with first 5 payloads
            try:
                # Test as URL parameter
                test_url = f"{self.target_url}?test={payload}"
                response = self.session.get(test_url, timeout=self.timeout)
                results['total_requests'] += 1

                # Check if request was blocked
                if response.status_code in [403, 406, 429, 501, 503]:
                    results['blocked_requests'] += 1

                    # Try to identify WAF from response
                    for waf_name, signatures in self.WAF_SIGNATURES.items():
                        if 'response_text' in signatures:
                            for pattern in signatures['response_text']:
                                if pattern.lower() in response.text.lower():
                                    results['detected'] = True
                                    results['waf_type'] = waf_name
                                    results['confidence'] = 80
                                    results['evidence'].append(
                                        f"WAF signature found in response: '{pattern}'"
                                    )
                                    break

                # Rate limiting
                time.sleep(0.5)

            except Exception as e:
                logger.debug(f"Payload test error: {e}")
                continue

        return results

    def _test_rate_limiting(self) -> Dict[str, Any]:
        """Test for rate limiting"""
        results = {
            'detected': False,
            'evidence': ''
        }

        try:
            # Make rapid requests
            responses = []
            for i in range(10):
                response = self.session.get(self.target_url, timeout=self.timeout)
                responses.append(response.status_code)
                time.sleep(0.1)

            # Check if we got rate limited
            if 429 in responses or 503 in responses:
                results['detected'] = True
                results['evidence'] = f"Rate limiting detected: Status codes {responses}"
                logger.info("Rate limiting detected")

        except Exception as e:
            logger.debug(f"Rate limit test error: {e}")

        return results

    def _generate_recommendations(self, results: Dict[str, Any]) -> List[str]:
        """Generate testing recommendations based on WAF detection"""
        recommendations = []

        if results['waf_detected']:
            recommendations.append(
                "WAF detected - Testing may be blocked or rate-limited"
            )
            recommendations.append(
                f"Identified WAF: {results['waf_type']} (confidence: {results['confidence']}%)"
            )
            recommendations.append(
                "Consider using evasion techniques: encoding, case variation, fragmentation"
            )
            recommendations.append(
                "Test during low-traffic periods to avoid rate limiting"
            )

            # WAF-specific recommendations
            if 'Cloudflare' in results['waf_type']:
                recommendations.append(
                    "Cloudflare detected - Direct origin IP discovery may bypass WAF"
                )
            elif 'ModSecurity' in results['waf_type']:
                recommendations.append(
                    "ModSecurity detected - Check for rule set version and exclusions"
                )
        else:
            recommendations.append(
                "No WAF detected - Standard testing approaches should work"
            )
            recommendations.append(
                "Still use caution - lightweight WAF may be present"
            )

        if results['rate_limiting']:
            recommendations.append(
                "Rate limiting active - Reduce request frequency"
            )

        return recommendations


def quick_waf_check(target_url: str) -> Dict[str, Any]:
    """
    Quick WAF detection check (convenience function)

    Args:
        target_url: Target URL to check

    Returns:
        WAF detection results
    """
    detector = WAFDetector(target_url)
    return detector.detect_waf()
